### ISSUE TITLE
structure.json and mysql settings missing

### ISSUE THREAD

**Issue by h-teske** [sstadlberger/home#1]
Hi!

Great job! I'm really happy I found your repo. With a bit of fiddling I managed to run your code and can now switch my lights via the API.

Unfortunately the structure.json is not included in the repo. Would be awesome if you told me what format it should have. Same is with the MySQL configuration.

Many thanks again,
Holger

**Comment by h-teske** [comment]
I created a working structure.json file (see pull request)

**Comment by sstadlberger** [comment]
Thanks!

Solved in #2 and d17074531f30a80603c6caee5fe9dd052f732b30
