### ISSUE TITLE
SysAP 2.1.5 not working properly

### ISSUE THREAD

**Issue by bochede** [sstadlberger/home#10]
i updated my AP und now i have several erros, for example 
 - no actual temperature from room temperature sensor - i get only an old value 
 - no value for the standing of blinds - i do not even see the values in 'info'

**Comment by sstadlberger** [comment]
I can confirm that. I still have some issues with 2.1.5 on my SysAP. When the issues are resolved I'll start updating the software.

(Maybe related to #6?)

**Comment by sstadlberger** [comment]
The thermostat issue should be fixed in 7dab93b57a13dd24bf1caebd437c91ad2eda24af and 5da7d8d43c1b6ad2c72c6c41c1b45b690210c377

**Comment by sstadlberger** [comment]
@bochede After some testing I think that the issue with the blinds is not related to the software but to the actuator. I had the same problem but managed to solve it:

Another symptom was that I had the following message for the affected channels in the SysAP Software that would not go away even after following the calibration steps:

> Mitteilungen:
> Bitte kalibrieren Sie die Jalousie durch das einmalige, vollständige Fahren nach oben.

I had the problem on multiple channels on one of my four actuators (Jalousieaktor 4-fach, REG), both on shutter (Rolladen) and blinds (Jalousie) settings.

I had to reset and reconfigure the actuator to get it working again (Gerätekonfiguration > Aktor auswählen > Wartung > Zurücksetzen). Afterwards everything was working again.

I think, the 2.1.5 is pretty buggy. After the update I had to call Busch Jaeger just the get the basics working again. Half of my sensors and actuators stopped working after the update and had to be reset to work again.

Hope this helps.

**Comment by sstadlberger** [comment]
I just found that there is still a small issue with blinds. I'm working on it.

**Comment by sstadlberger** [comment]
The shutter blind required only a small change, only two datapoints were moved. Fixed in edea292c3fa5b3d0ce770103018c58042e94ca7f and e2a7694cebb0d56219b5fa7c6043a67983421fb1.

**Comment by sstadlberger** [comment]
It's been working now for me for two weeks. I'm closing this issue. Please open another one if you still find any problems.
