### ISSUE TITLE
Receive information about pressed switches/buttons

### ISSUE THREAD

**Issue by henry-spanka** [sstadlberger/home#14]
Hello,
is it possible to receive a message via web socket for example if a switch is pressed?

**Comment by sstadlberger** [comment]
Yes, that would be technically possible. If I remember correctly the BJ SysAP sends out an event notification for every action (i.e. switch pressed, switch released, etc.). Right now that information is ignored and only the status of the actuators is parsed.

It would be possible to include the information in a separate web socket stream, but it will probably take a while until all possible event/sensor combinations are analysed and implemented.

As a short term solution it would be possible to expose the raw SysAP data to a web socket stream and leave it to the receiving application to parse the data. Would that be helpful to you?

You can see the raw data when you start home with the --logLevel=trace option.

Stefan

**Comment by henry-spanka** [comment]
Thanks. Didn't know about the `--logLevel=trace` option. That's exactly what I need.
Maybe convert it to JSON first and strip out all the trash. Only the actuator serial, channel and datapoint is important.
Response should be similar to the `info` command if possible.
