### ISSUE TITLE
could you add these device ids?

### ISSUE THREAD

**Issue by victorclaessen** [sstadlberger/home#16]
Could you perhaps add the following device ids? Because now these device id's aren't recognised as dimmers.

1019: Sensor/Dimmaktor 2/1-fach
1017: Sensor/Dimmaktor 1/1-fach

Example from REST API call to info/ABB700C8xxxx:

`{"serialNumber":"ABB700C8xxxx","deviceId":"1019","typeName":"Sensor/Dimmaktor 2/1-fach","channels":{"ch0006":{"datapoints":{"idp0000":"0","idp0001":"0","idp0002":"0","idp0005":"6","idp0006":"1","odp0000":"0","odp0001":"0","odp0002":"0","odp0003":"0","pm0000":"2","pm0001":"5","pm0002":"50","pm0003":"20","pm0004":"60","pm0005":"2"}}}}`

**Comment by sstadlberger** [comment]
Done in 1da44f68b46ddb06ce5197f7361b2f305f1bb1f5

Can't test it because I don't have the devices. Please comment if there are any problems, otherwise I will code this issue in about a week.

**Comment by victorclaessen** [comment]
Hi Stefan,

Yes I can confirm that it works. I can address the devices as dimmers now. Great!

Thanks,

Victor
