### ISSUE TITLE
Dimmers not working?

### ISSUE THREAD

**Issue by martin072** [sstadlberger/home#30]
Hi,

I finally moved in to my new house and had a play with Free@Home, and it works like perfect. I really prefer this option as I have my own custom home automation implementation, and have not at all looked into openHab, so I really hope you can keep on supporting this. 

I have a small question about dimmers, for some reason they won't work when using the following url:

/set/dimmer/<address>/ch0000/on
Result:
set channel ch0000 of dimmer <address> (Hue Aktor) to on: <address>/ch0000/idp0000: 1
and the debug log:
2019-09-04 1:01:01 PM [debug] [x.x.x.x] web set channel ch0000 of dimmer <address> to on
2019-09-04 1:01:01 PM [debug] set actuator: <address>/ch0000/idp0000: 1
2019-09-04 1:01:01 PM [debug] result packet received
2019-09-04 1:01:01 PM [debug] result update succes

This is a Hue light, but I also tried a B+J Dimmer, same result, lights don't go on

**Comment by sstadlberger** [comment]
Hi,

Hue actuators should not work as they use a different syntax (which I haven't looked at). You might get it to work with the /raw/serialnumber/channel/datapoint/value command.

/set/dimmer/ch000x/on should work (I worked for me with the 6252/0.4-101 actuator). I can't test it anymore as I have moved my installation to openHab.

Maybe check if you have the correct channel? Some actuators don't start with ch0000 but for example ch0009. You can get more information with /info/serialnumber for a device.

Cheers,
Stefan

**Comment by martin072** [comment]
Thanks, was indeed another channel. Hue devices work fine as will. They use the syntax dimmer for me ch0000 works perfect.
